version: "3"

dotenv:
  - .env
tasks:
  login:
    - echo "Password is $NUV_PASSWORD"
    - nuv -login $NUV_HOST $NUV_USER
  default:
    - task: deploy
  deploy:
    dir: packages
    cmds:
      - wsk project deploy
